controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_controller:
      type: joint_state_controller/JointStateController

velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_front_hinge
      - right_wheel_front_hinge
      - left_wheel_back_hinge
      - right_wheel_back_hinge
