controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_controller:
      type: joint_state_controller/JointStateController

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

velocity_controller:
  ros__parameters:
    joints:
      - left_wheel_front_hinge
      - right_wheel_front_hinge
      - left_wheel_back_hinge
      - right_wheel_back_hinge

diff_drive_controller:
  ros__parameters:
    left_wheel_names: [ 'left_wheel_front_hinge', 'left_wheel_back_hinge' ]
    right_wheel_names: [ 'right_wheel_front_hinge', 'right_wheel_back_hinge' ]

    # Separation between a left and right wheel in meters
    wheel_separation: 0.4

    wheel_radius: 0.18

    # Setting the timeout to INT_MAX (~68 years) until we can migrate all of our
    # controllers to publish commands continuously instead of discretely.
    #
    # This timeout means that when a controller receives a message, it will cancel the message if 
    # another message has not been received in X amount of time, where x is the timeout value.
    #
    # The mobile app currently works by only sending a message when a movement is intended,
    # and then another message when the robot should stop.
    cmd_vel_timeout: 2147483647

    # Publish the odometry to separate topic or not; false to work w/ Kalman Filter
    enable_odom_tf: false

    # Default covariance values from example on diff drive controller wiki
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Frame of rover
    base_frame_id: base_link

    # The ratio of max acc and max vel is same as skid steer example in diff drive controlller wiki
    # Note: Could also include for constraints for angular but linear caps ensure rover doesn't rotate too fast
    linear:
      x:
        has_velocity_limits    : true

        # Actual speed of rover is 1 meter per 3 secs, so this is sped up
        max_velocity           : 1.0  # m/s

        # Match backwards speed cap
        min_velocity           : -1.0 # m/s

        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
